---
#
# Copyright (C) 2020-2026 James Cherti
# URL: https://github.com/jamescherti/ansible-role-apt
#
# Distributed under terms of the MIT license.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

#
# main: free
# contrib: free (but depends on non-free software)
# non-free*: non free software
#
- name: Update /etc/apt/sources.list
  notify: Apt-get update
  ansible.builtin.copy:
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: "0644"
    content: |
      {% for suffix in ["", "-src"] %}
      deb{{ suffix }} {{ apt_mirror_url_debian }} {{ apt_distribution_codename }} main{{ '' if not apt_debian_community else ' contrib' }}{{ '' if not apt_debian_nonfree else ' non-free non-free-firmware' }}
      deb{{ suffix }} {{ apt_mirror_url_debian }} {{ apt_distribution_codename }}-updates main{{ '' if not apt_debian_community else ' contrib' }}{{ '' if not apt_debian_nonfree else ' non-free non-free-firmware' }}
      deb{{ suffix }} {{ apt_mirror_url_debian_security }} {{ apt_distribution_codename }}-security main{{ '' if not apt_debian_community else ' contrib' }}{{ '' if not apt_debian_nonfree else ' non-free non-free-firmware' }}
      {% endfor %}

      {% for suffix in ["", "-src"] %}
      {% if apt_debian_backports | bool %}
      deb{{ suffix }} {{ apt_mirror_url_debian }} {{ apt_distribution_codename }}-backports main{{ '' if not apt_debian_community else ' contrib' }}{{ '' if not apt_debian_nonfree else ' non-free non-free-firmware' }}
      {% else %}
      # deb{{ suffix }} {{ apt_mirror_url_debian }} {{ apt_distribution_codename }}-backports main{{ '' if not apt_debian_community else ' contrib' }}{{ '' if not apt_debian_nonfree else ' non-free non-free-firmware' }}
      {% endif %}
      {% endfor %}

- name: Import Tasks from debian_backport.yaml
  when: apt_debian_backports_packages != ""
  ansible.builtin.import_tasks: "debian_backport.yaml"
  tags: debian_backport
